version: '3'
services:
  db:
    image: postgres
    environment:
        POSTGRES_DB: eikondb
        POSTGRES_USER: eikon
        POSTGRES_PASSWORD: eikon123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
